const constants = {
  START_LOADER: 'START_LOADER',
  STOP_LOADER: 'STOP_LOADER',
  SET_BOOKS_COLLECTION: 'SET_BOOKS_COLLECTION',
  CREATE_BOOK: 'CREATE_BOOK',
  REMOVE_BOOK: 'REMOVE_BOOK',
  CHANGE_FILTER: 'CHANGE_FILTER'
}

export default constants
